### ISSUE TITLE
Create Test for "Recipes generation"

### ISSUE THREAD

**Issue by 18chanp1** [18chanp1/cpen321-recipe-roulette#45]

**Comment by valentino-jaber** [comment]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-75c0b869-7fff-c618-2f7d-eae4f1aeacf5"><div dir="ltr" style="margin-left:0pt;" align="left">
checkGenerateRecipesButtonVisible | Tests the generate recipe button is displayed
-- | --
checkGenerateRecipesButtonAndCheckRecipeList | Tests the presence of recipe list after generating recipe

</div></b>
