### ISSUE TITLE
Create test for Recipes upload

### ISSUE THREAD

**Issue by 18chanp1** [18chanp1/cpen321-recipe-roulette#46]

**Comment by valentino-jaber** [comment]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-a59563ab-7fff-8d3c-5dff-4a86df8f5617"><div dir="ltr" style="margin-left:0pt;" align="left">
checkCameraButtonVisible | Tests the camera upload button is displayed initially
-- | --
checkGalleryButtonVisible | Tests the gallery upload button is displayed initially
checkManualEntryButtonVisible | Tests the manual upload button is displayed initially
checkSendImageButtonNotVisibleInitially | Tests the send image button is not displayed initially
captureImageAndCheckSendButton | Tests camera image capture and send button appears
selectImageFromGalleryAndCheckSendButton | Tests gallery image selection and send button appears
enterGroceryItemInManualEntryDialog | Tests sample grocery manual entry
cancelManualEntryDialog | Tests cancelling manual entry

</div></b>

**Comment by 18chanp1** [comment]
looks good, approve the merge
